### ISSUE TITLE
Unit-tests and consistency check with MLINK program

### ISSUE THREAD

**Issue by gaow** [magnusdv/paramlink2#1]
@magnusdv this is very helpful work for those who perform linkage analysis! We have been trying it and it seems to work great. However we are still weighing between using paramlink2 vs [an mlink wrapper from Jurg Ott](https://www.jurgott.org/linkage/runLINK.html) to use as our linkage analysis pipeline. The only concern I have right now is that (with due respect) the mlink suite has been working well for the past few decades and has features to handle many corner cases particularly with Jurg's wrapper and modifications. Specifically:

1. Are all the features in mlink suite, particularly those QC on input data before running linkage analysis, also implemented in paramlink2?
2. Is there some evaluations on real data on consistency in results between mlink and paramlink2? I dont see those in unit tests but it would be helpful to share those results with users if you have performed comparisons
3. Apart from the tremendously improved user experience and the new visualization feature, are there additional features that makes it more appealing to use paramlink2 compared to traditional linkage suites? (we can limit that to compare with mlink, although other packages such as superlink and ilink have additional features over mlink that I'm not sure if is also part of paramlink2 improvements)

Thank you!

**Comment by magnusdv** [comment]
Hi, many thanks for your interest in paramlink2. 

1. I am sure the answer is "no", although I don't know mlink intimately enough to pinpoint the differences. To the defence of paramlink2 one might say that R encourages a more transparent workflow than traditional black box programs. The *ped suite* (which paramlink2 is a part of) contains a variety of functions for analysing and checking datasets, like `pedtools::mendelianCheck()` which looks for Mendelian errors in the marker data.
2. I agree that such public validation would be valuable. paramlink2 has been thoroughly tested (mostly against MERLIN) but as you say these comparisons are not currently included in the unit tests or available elsewhere.
3. Well, one thing that is very easy in paramlink2, and which I personally find helpful, is to compute both singlepoint and multipoint LODs and plot them together. I also find downstream analysis to be quite efficient, with utilities like `peakSummary()` before proceeding with *biomaRt* and similar packages.

I hope this provided some answers. Don't hesitate to ask again if you have further questions.
