### ISSUE TITLE
Individual 22B25641701 has exactly 1 parent; this is not allowed

### ISSUE THREAD

**Issue by liuhankui** [magnusdv/paramlink2#2]
paramlink2 can only use the participants with the father and mother.
However, in some cases, we can only observe a child and one of the parents.

**Comment by magnusdv** [comment]
Yes, all *ped suite* packages, including paramlink2, require both parents to be included in the pedigree. If you are loading a ped file, it shouldn't be too much trouble to add the missing parents manually.

**Comment by liuhankui** [comment]
> 
Got it, ped file accepts missing parents.
Thank you^_^.
