### ISSUE TITLE
LOD scores are NaN

### ISSUE THREAD

**Issue by MahShaaban** [magnusdv/paramlink2#3]
Hi @magnusdv A quick question.
Other than the incompatible mutational patterns, why are the LOD scores of all markers NaN?

**Comment by magnusdv** [comment]
Hi, can you provide a reproducible example?
Thanks.

**Comment by MahShaaban** [comment]
It could be a specific thing to my data. I am asking for an advice.
There was a sentence in`pramlink` docs about inconsistent markers, but it is not there in `paramlink2`!
The examples given in the docs reproduce just fine.

**Comment by magnusdv** [comment]
Ok, if you encounter any specific problems, I'd be happy to take a look if you provide a reproducible example.

Some general advice when seeking help:
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

I strongly recommend the reprex package: https://github.com/tidyverse/reprex

**Comment by MahShaaban** [comment]
Thanks.
